### ISSUE TITLE
[QUESTION]: Safe Income

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/FMTransactionTriggerer#1]
Hello Arthur,

With GTA Online 1.69, R* added a mobile app that players can use to collect income from their safes without having to spend 10 years between interior/exterior loading screens. But, typically they locked it behind a paywall and most importantly, made it impossible to have on PC because it's exclusive to GTA+ members.

I've been trying to figure this out since the update dropped, I tried looking at decompiled scripts, manually collecting income hoping to catch something but I'm not a reverse engineer so I yielded no results.

My question is, can this script or your work on exposing script functions to Lua be used to collect safe income?

Thanks and sorry for opening an issue! I didn't think it was appropriate to contact you in private about this.

**Comment by ShinyWasabi** [comment]
I just took a quick look, and unfortunately there is no way of collecting the safe income unless you are in the property because the functions only exist in the ambient scripts. Maybe I can try to start the scripts through am_launcher and then call the function, but IDK how efficient it would be.

**Comment by xesdoog** [comment]
I had a feeling that it wouldn't be so simple since it's literally locked behind a paywall but oh well, at least we tried.

Thanks for taking the time to look at it, I appreciate you.
